---
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2022.2.5"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    # should run on the network of its host
    network_mode: host
    # port 5683 is for Shelly CoIoT
    ports:
      - "8123:8123"
      - "5683:5683/udp"

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    user: mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.23.0
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - "${ZIGBEE_DEVICE}:/dev/ttyACM0"
    environment:
      - "TZ=${TZ}"
      - "ZIGBEE2MQTT_CONFIG_HOMEASSISTANT=${ZIGBEE2MQTT_CONFIG_HOMEASSISTANT}"
      - "ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=${ZIGBEE2MQTT_CONFIG_PERMIT_JOIN}"
      - "ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=${ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC}"
      - "ZIGBEE2MQTT_CONFIG_MQTT_SERVER=${ZIGBEE2MQTT_CONFIG_MQTT_SERVER}"
      - "ZIGBEE2MQTT_CONFIG_USER=${ZIGBEE2MQTT_CONFIG_USER}"
      - "ZIGBEE2MQTT_CONFIG_PASSWORD=${ZIGBEE2MQTT_CONFIG_PASSWORD}"
      - "ZIGBEE2MQTT_CONFIG_INCLUDE_DEVICE_INFORMATION=${ZIGBEE2MQTT_CONFIG_INCLUDE_DEVICE_INFORMATION}"
      - "ZIGBEE2MQTT_CONFIG_SERIAL_PORT=${ZIGBEE_DEVICE}"
      - "ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED=${ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED}"
      - "ZIGBEE2MQTT_CONFIG_QUEUE_DELDAY=${ZIGBEE2MQTT_CONFIG_QUEUE_DELDAY}"
      - "ZIGBEE2MQTT_CONFIG_QUEUE_SIMULTANEOUSLY=${ZIGBEE2MQTT_CONFIG_QUEUE_SIMULTANEOUSLY}"
    ports:
      - "8080:8080"
