---
# Garage covers
- platform: template
  covers:
    garage_front_door:
      device_class: garage
      friendly_name: "Garage Rolltor"
      value_template: >-
        {% if is_state('binary_sensor.shelly_dw_garage_01_door','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_2
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_2
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_2
      icon_template: >-
        {% if is_state('binary_sensor.shelly_dw_garage_01_door','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

- platform: template
  covers:
    garage_back_door:
      device_class: garage
      friendly_name: "Garage Schwingtor"
      value_template: >-
        {% if is_state('binary_sensor.shelly_dw_garage_02_door','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_1
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_1
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.shelly_uni_garage_01_channel_1
      icon_template: >-
        {% if is_state('binary_sensor.shelly_dw_garage_02_door','on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
