---
# MQTT based switches
- platform: "mqtt"
  # 0x7cb03eaa0a02ddb9
  name: "osram-dose-01"
  icon: mdi:switch
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "zigbee2mqtt/osram-dose-01/get"
  state_on: "ON"
  state_off: "OFF"
  command_topic: "zigbee2mqtt/osram-dose-01/set"
  qos: 1

- platform: "mqtt"
  # 0xec1bbdfffeaea623
  name: "IKEA-sw-01"
  icon: mdi:switch
  payload_on: "on"
  payload_off: "off"
  state_topic: "zigbee2mqtt/IKEA_sw_01/get"
  state_on: "on"
  state_off: "off"
  command_topic: "zigbee2mqtt/IKEA_sw_01/set"
  qos: 1
